"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import { useDropzone } from "react-dropzone";
import { AnalysisResult } from "@/types";
import { analyzeResumeText, analyzeResumePDF } from "@/lib/api";
import ATSScoreRing from "@/components/ATSScoreRing";
import SectionCard from "@/components/SectionCard";
import LoadingSkeleton from "@/components/LoadingSkeleton";

type InputMode = "text" | "pdf";

function generateReport(result: AnalysisResult): string {
  const lines: string[] = [
    "RESUME ENHANCEMENT REPORT",
    "Generated by Resumé Edge",
    "=".repeat(50),
    "",
    `ATS SCORE: ${result.ats_score}/100`,
    result.ats_score_explanation,
    "",
    "OVERALL ASSESSMENT",
    "-".repeat(30),
    result.overall_summary,
    "",
    "QUICK WINS",
    "-".repeat(30),
    ...result.quick_wins.map((w, i) => `${i + 1}. ${w}`),
    "",
    "MISSING KEYWORDS",
    "-".repeat(30),
    result.keywords_missing.join(", "),
    "",
    "SECTION-BY-SECTION ANALYSIS",
    "=".repeat(50),
  ];

  for (const section of result.sections) {
    lines.push(`\n${section.name.toUpperCase()} [${section.status.replace("_", " ").toUpperCase()}]`);
    lines.push("-".repeat(30));
    if (section.strengths.length) {
      lines.push("Strengths:");
      section.strengths.forEach((s) => lines.push(`  - ${s}`));
    }
    if (section.improvements.length) {
      lines.push("Improvements:");
      section.improvements.forEach((s) => lines.push(`  - ${s}`));
    }
    if (section.rewritten_example) {
      lines.push(`Rewrite Example:\n  ${section.rewritten_example}`);
    }
  }

  return lines.join("\n");
}



export default function HomePage() {
  const [inputMode, setInputMode] = useState<InputMode>("text");
  const [resumeText, setResumeText] = useState("");
  const [jobRole, setJobRole] = useState("");
  const [pdfFile, setPdfFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [showExtracted, setShowExtracted] = useState(false);
  const [experienceLevel, setExperienceLevel] = useState("");

  /* ── Cursor-following glow ── */
  const heroRef = useRef<HTMLDivElement>(null);
  const [glowPos, setGlowPos] = useState({ x: 50, y: 50 });

  useEffect(() => {
    const el = heroRef.current;
    if (!el) return;
    const onMove = (e: MouseEvent) => {
      const rect = el.getBoundingClientRect();
      const x = ((e.clientX - rect.left) / rect.width) * 100;
      const y = ((e.clientY - rect.top) / rect.height) * 100;
      setGlowPos({ x, y });
    };
    el.addEventListener("mousemove", onMove);
    return () => el.removeEventListener("mousemove", onMove);
  }, [result, loading]);

  /* ── Canvas cursor trail — Antigravity-style particle system ── */
  useEffect(() => {
    const canvas = document.createElement("canvas");
    canvas.style.cssText = "position:fixed;inset:0;pointer-events:none;z-index:9999;";
    document.body.appendChild(canvas);
    const ctx = canvas.getContext("2d")!;
    let w = 0, h = 0;
    const resize = () => { w = canvas.width = window.innerWidth; h = canvas.height = window.innerHeight; };
    resize();
    window.addEventListener("resize", resize);

    // Mouse state
    let mouseX = w / 2, mouseY = h / 2;
    let smoothX = mouseX, smoothY = mouseY;
    let prevX = mouseX, prevY = mouseY;
    let isMoving = false;
    let moveTimer = 0;

    const onMove = (e: MouseEvent) => {
      mouseX = e.clientX;
      mouseY = e.clientY;
      isMoving = true;
      clearTimeout(moveTimer);
      moveTimer = window.setTimeout(() => { isMoving = false; }, 80);
    };
    document.addEventListener("mousemove", onMove);

    // Trail history (smooth ribbon)
    const trail: { x: number; y: number; age: number }[] = [];
    const TRAIL_LENGTH = 20;
    const TRAIL_LIFETIME = 300; // ms

    // Particle system
    interface Particle {
      x: number; y: number;
      vx: number; vy: number;
      size: number;
      color: string;
      alpha: number;
      life: number;
      maxLife: number;
      phase: number;
    }
    const particles: Particle[] = [];
    const COLORS = ["#C8F135", "#C8F135", "#111927", "#6b7280"]; // lime weighted heavier
    const MAX_PARTICLES = 50;
    let spawnAccum = 0;

    const spawn = (x: number, y: number, speed: number) => {
      if (particles.length >= MAX_PARTICLES) return;
      const angle = Math.random() * Math.PI * 2;
      const force = 0.3 + Math.random() * 0.8;
      particles.push({
        x, y,
        vx: Math.cos(angle) * force + (Math.random() - 0.5) * 0.5,
        vy: -1.2 - Math.random() * 1.5 + Math.sin(angle) * force * 0.5,
        size: 2 + Math.random() * 5,
        color: COLORS[Math.floor(Math.random() * COLORS.length)],
        alpha: 0.6 + Math.random() * 0.3,
        life: 0,
        maxLife: 50 + Math.random() * 40,
        phase: Math.random() * Math.PI * 2,
      });
      if (speed > 4 && Math.random() > 0.5 && particles.length < MAX_PARTICLES) {
        particles.push({
          x: x + (Math.random() - 0.5) * 8,
          y: y + (Math.random() - 0.5) * 8,
          vx: (Math.random() - 0.5) * 2,
          vy: -2 - Math.random() * 2,
          size: 1.5 + Math.random() * 2,
          color: "#C8F135",
          alpha: 0.8,
          life: 0,
          maxLife: 25 + Math.random() * 20,
          phase: Math.random() * Math.PI * 2,
        });
      }
    };

    let lastFrame = performance.now();
    let animId = 0;

    const loop = (now: number) => {
      animId = requestAnimationFrame(loop);
      const dt = Math.min((now - lastFrame) / 16.667, 3);
      lastFrame = now;
      ctx.clearRect(0, 0, w, h);

      smoothX += (mouseX - smoothX) * 0.15;
      smoothY += (mouseY - smoothY) * 0.15;

      const speed = Math.sqrt((smoothX - prevX) ** 2 + (smoothY - prevY) ** 2);

      if (isMoving && speed > 1.5) {
        spawnAccum += speed * 0.12 * dt;
        while (spawnAccum >= 1) {
          spawnAccum--;
          const t = Math.random();
          const sx = prevX + (smoothX - prevX) * t;
          const sy = prevY + (smoothY - prevY) * t;
          spawn(sx, sy, speed);
        }
      }

      if (isMoving && speed > 0.5) {
        trail.unshift({ x: smoothX, y: smoothY, age: 0 });
      }
      for (let i = trail.length - 1; i >= 0; i--) {
        trail[i].age += 16.667 * dt;
        if (trail[i].age > TRAIL_LIFETIME) { trail.splice(i, 1); continue; }
      }
      if (trail.length > TRAIL_LENGTH) trail.length = TRAIL_LENGTH;

      if (trail.length > 2) {
        ctx.beginPath();
        ctx.moveTo(trail[0].x, trail[0].y);
        for (let i = 1; i < trail.length; i++) {
          const prev = trail[i - 1];
          const curr = trail[i];
          const mx = (prev.x + curr.x) / 2;
          const my = (prev.y + curr.y) / 2;
          ctx.quadraticCurveTo(prev.x, prev.y, mx, my);
        }
        ctx.strokeStyle = "rgba(200, 241, 53, 0.08)";
        ctx.lineWidth = 24;
        ctx.lineCap = "round";
        ctx.stroke();
      }

      const glowAlpha = Math.min(speed * 0.008, 0.12);
      if (glowAlpha > 0.01) {
        const grad = ctx.createRadialGradient(smoothX, smoothY, 0, smoothX, smoothY, 120);
        grad.addColorStop(0, `rgba(200, 241, 53, ${glowAlpha})`);
        grad.addColorStop(0.5, `rgba(200, 241, 53, ${glowAlpha * 0.3})`);
        grad.addColorStop(1, "rgba(200, 241, 53, 0)");
        ctx.fillStyle = grad;
        ctx.fillRect(smoothX - 120, smoothY - 120, 240, 240);
      }

      for (let i = particles.length - 1; i >= 0; i--) {
        const p = particles[i];
        p.life += dt;
        if (p.life >= p.maxLife) { particles.splice(i, 1); continue; }

        const progress = p.life / p.maxLife;
        const ease = 1 - progress;

        p.vy -= 0.02 * dt;
        p.vx += Math.sin(p.life * 0.08 + p.phase) * 0.03 * dt;
        p.vx *= 0.995;
        p.vy *= 0.995;
        p.x += p.vx * dt;
        p.y += p.vy * dt;

        const alpha = p.alpha * ease * ease;
        const scale = 0.3 + ease * 0.7;
        const r = p.size * scale;

        if (alpha < 0.01) continue;

        ctx.globalAlpha = alpha;

        if (p.color === "#C8F135" && r > 2) {
          const glow = ctx.createRadialGradient(p.x, p.y, 0, p.x, p.y, r * 3);
          glow.addColorStop(0, `rgba(200, 241, 53, ${alpha * 0.3})`);
          glow.addColorStop(1, "rgba(200, 241, 53, 0)");
          ctx.fillStyle = glow;
          ctx.fillRect(p.x - r * 3, p.y - r * 3, r * 6, r * 6);
        }

        ctx.beginPath();
        ctx.arc(p.x, p.y, r, 0, Math.PI * 2);
        ctx.fillStyle = p.color;
        ctx.fill();
      }

      ctx.globalAlpha = 1;
      prevX = smoothX;
      prevY = smoothY;
    };

    animId = requestAnimationFrame(loop);

    return () => {
      cancelAnimationFrame(animId);
      document.removeEventListener("mousemove", onMove);
      window.removeEventListener("resize", resize);
      clearTimeout(moveTimer);
      canvas.remove();
    };
  }, []);

  const onDrop = useCallback((acceptedFiles: File[]) => {
    if (acceptedFiles[0]) {
      setPdfFile(acceptedFiles[0]);
      setError(null);
    }
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: { "application/pdf": [".pdf"] },
    maxFiles: 1,
    maxSize: 5 * 1024 * 1024,
    onDropRejected: (files) => {
      const code = files[0]?.errors[0]?.code;
      if (code === "file-too-large") setError("File too large. Max size is 5MB.");
      else setError("Please upload a valid PDF file.");
    },
  });

  const handleAnalyze = async () => {
    setError(null);
    setResult(null);
    setLoading(true);
    setShowExtracted(false);

    try {
      let data: AnalysisResult;
      if (inputMode === "text") {
        if (!resumeText.trim() || resumeText.trim().length < 50) {
          throw new Error("Please paste your resume content (at least 50 characters).");
        }
        data = await analyzeResumeText(resumeText, jobRole, experienceLevel);
      } else {
        if (!pdfFile) throw new Error("Please upload a PDF file.");
        data = await analyzeResumePDF(pdfFile, jobRole, experienceLevel);
      }
      setResult(data);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Something went wrong. Please try again.";
      setError(msg);
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setResult(null);
    setError(null);
    setResumeText("");
    setPdfFile(null);
    setShowExtracted(false);
    setExperienceLevel("");
    setJobRole("");
  };

  const handleDownload = () => {
    if (!result) return;
    const content = generateReport(result);
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "resume-feedback.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const canAnalyze = inputMode === "text" ? resumeText.trim().length >= 50 : !!pdfFile;

  /* ── Springy scale helpers for interactive elements ── */
  const springTransition = "transform 0.18s cubic-bezier(0.34, 1.56, 0.64, 1)";
  const springBtn = {
    onMouseEnter: (e: React.MouseEvent<HTMLElement>) => { e.currentTarget.style.transform = "scale(1.08)"; },
    onMouseLeave: (e: React.MouseEvent<HTMLElement>) => { e.currentTarget.style.transform = "scale(1)"; },
    onMouseDown:  (e: React.MouseEvent<HTMLElement>) => { e.currentTarget.style.transform = "scale(0.97)"; },
    onMouseUp:    (e: React.MouseEvent<HTMLElement>) => { e.currentTarget.style.transform = "scale(1.08)"; },
  };

  return (
    <div className="min-h-screen" style={{ fontFamily: "var(--font-body)" }}>

      {/* Header */}
      <header
        className="border-b sticky top-0 z-10 backdrop-blur-sm"
        style={{ borderColor: "var(--border)", background: "rgba(255,255,255,0.85)" }}
      >
        <div className="max-w-5xl mx-auto px-4 py-3 flex items-center justify-between">
          <span style={{ fontFamily: "var(--font-display)", fontSize: "1.3rem", fontWeight: 700, color: "var(--ink)" }}>Resumé Edge</span>
          <div className="flex items-center gap-3">
            {result && (
              <button
                onClick={handleReset}
                className="text-sm px-3 py-1.5 rounded-lg border"
                style={{ borderColor: "var(--border)", color: "var(--muted)", cursor: "pointer", transition: springTransition }}
                {...springBtn}
              >
                ← New Analysis
              </button>
            )}
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 py-10">
        {/* ---- INPUT VIEW ---- */}
        {!result && !loading && (
          <>
            {/* ═══ Hero section ═══ */}
            <div
              ref={heroRef}
              className="hero-bg text-center mb-10 py-16 px-4 rounded-3xl"
              style={{ minHeight: "auto" }}
            >
              {/* ── Orb 1 — lime, 15% opacity, blur-100, 18s drift ── */}
              <div
                style={{
                  position: "absolute",
                  width: 380,
                  height: 380,
                  borderRadius: "50%",
                  background: "rgba(200, 241, 53, 0.15)",
                  top: "-70px",
                  right: "-50px",
                  filter: "blur(100px)",
                  animation: "orbDrift1 18s ease-in-out infinite",
                  pointerEvents: "none",
                  zIndex: 0,
                }}
              />
              {/* ── Orb 2 — dark ink, 10% opacity, blur-100, 14s drift ── */}
              <div
                style={{
                  position: "absolute",
                  width: 300,
                  height: 300,
                  borderRadius: "50%",
                  background: "rgba(17, 25, 39, 0.10)",
                  bottom: "-40px",
                  left: "-30px",
                  filter: "blur(100px)",
                  animation: "orbDrift2 14s ease-in-out infinite",
                  pointerEvents: "none",
                  zIndex: 0,
                }}
              />
              {/* ── Orb 3 — grey, 20% opacity, blur-100, 10s drift ── */}
              <div
                style={{
                  position: "absolute",
                  width: 260,
                  height: 260,
                  borderRadius: "50%",
                  background: "rgba(229, 229, 229, 0.20)",
                  top: "30%",
                  left: "55%",
                  filter: "blur(100px)",
                  animation: "orbDrift3 10s ease-in-out infinite",
                  pointerEvents: "none",
                  zIndex: 0,
                }}
              />

              {/* ── Cursor-following glow — lime tint, opacity-20 ── */}
              <div
                style={{
                  position: "absolute",
                  inset: 0,
                  borderRadius: "inherit",
                  background: `radial-gradient(600px circle at ${glowPos.x}% ${glowPos.y}%, rgba(200,241,53,0.20) 0%, transparent 60%)`,
                  pointerEvents: "none",
                  zIndex: 0,
                  transition: "background 0.15s ease-out",
                }}
              />

              {/* ── Hero content — z-index 10 ── */}
              <h1
                className="mb-3 relative"
                style={{
                  fontFamily: "var(--font-display)",
                  fontSize: "clamp(1.8rem, 6vw, 4rem)",
                  fontWeight: 700,
                  lineHeight: 1.1,
                  color: "var(--ink)",
                  zIndex: 10,
                }}
              >
                <span className="hero-line hero-line--1 block">Make your resume</span>
                <span className="hero-line hero-line--2 block">
                  <span className="underline-wipe">
                    impossible to ignore.
                  </span>
                </span>
              </h1>
              <p
                className="hero-line hero-line--3 text-base max-w-md mx-auto relative"
                style={{ color: "var(--muted)", zIndex: 10 }}
              >
                AI-powered analysis covering language, impact, structure, and ATS compatibility.
              </p>
            </div>

            {/* Feature pills — marquee ticker */}
            <div className="marquee-container my-6">
              <div className="marquee-track">
                {/* Two identical sets for seamless infinite loop */}
                {[0, 1].map((copy) =>
                  [
                    { label: "ATS Score", sub: "Compatibility check" },
                    { label: "Language Fix", sub: "Tone & clarity" },
                    { label: "Quick Wins", sub: "Instant improvements" },
                    { label: "Missing Keywords", sub: "Gap analysis" },
                  ].map(({ label, sub }) => (
                    <div key={`${copy}-${label}`} className="marquee-pill">
                      <div
                        style={{
                          fontFamily: "var(--font-display)",
                          fontWeight: 700,
                          fontSize: "0.95rem",
                          color: "var(--ink)",
                          letterSpacing: "0.01em",
                          marginBottom: "4px",
                        }}
                      >
                        {label}
                      </div>
                      <div
                        style={{
                          fontSize: "0.7rem",
                          color: "var(--muted)",
                          letterSpacing: "0.04em",
                          textTransform: "uppercase",
                        }}
                      >
                        {sub}
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>

            {/* Glassmorphism form card */}
            <div className="glass-card p-6 md:p-8">
              {/* Mode tabs with sliding indicator */}
              <div
                className="tab-group flex rounded-xl p-1 mb-6 w-fit"
                style={{ background: "var(--paper)", border: "1px solid var(--border)" }}
              >
                <div className="tab-indicator" data-active={inputMode} />
                {(["text", "pdf"] as InputMode[]).map((mode) => (
                  <button
                    key={mode}
                    onClick={() => { setInputMode(mode); setError(null); }}
                    className={`tab-btn px-4 py-2 rounded-lg text-sm font-medium transition-all ${inputMode === mode ? "tab-btn--active" : ""}`}
                    style={{
                      color: inputMode === mode ? "var(--accent-dark)" : "var(--muted)",
                      cursor: "pointer",
                      transition: springTransition,
                    }}
                    {...springBtn}
                  >
                    {mode === "text" ? "Paste Text" : "Upload PDF"}
                  </button>
                ))}
              </div>
               <div className="mb-5">
                  <label className="block text-xs font-medium mb-2 uppercase tracking-widest" style={{ color: "var(--muted)" }}>
                    Target Role / Industry <span style={{ color: "var(--muted)", fontWeight: 400 }}>(optional but recommended)</span>
                  </label>
                  <input
                    type="text"
                    value={jobRole}
                    onChange={(e) => setJobRole(e.target.value)}
                    placeholder="e.g. Data Analyst, Software Engineer, Product Manager, Marketing..."
                    className="input-glow w-full rounded-xl border px-4 py-3 text-sm focus:outline-none"
                    style={{
                      background: "var(--cream)",
                      borderColor: "var(--border)",
                      color: "var(--ink)",
                      fontFamily: "var(--font-body)",
                    }}
                  />
                </div>
                <div className="mb-5">
                  <label className="block text-xs font-medium mb-2 uppercase tracking-widest" style={{ color: "var(--muted)" }}>
                    Experience Level <span style={{ color: "var(--muted)", fontWeight: 400 }}>(optional but recommended)</span>
                  </label>
                  <select
                    value={experienceLevel}
                    onChange={(e) => setExperienceLevel(e.target.value)}
                    className="input-glow w-full rounded-xl border px-4 py-3 text-sm focus:outline-none"
                    style={{
                      background: "var(--cream)",
                      borderColor: "var(--border)",
                      color: experienceLevel ? "var(--ink)" : "var(--muted)",
                      fontFamily: "var(--font-body)",
                    }}
                  >
                    <option value="">Select experience level...</option>
                    <option value="student">Student / No Experience</option>
                    <option value="fresher">Fresher (0–1 years)</option>
                    <option value="junior">Junior (1–3 years)</option>
                    <option value="mid">Mid-level (3–6 years)</option>
                    <option value="senior">Senior (6–10 years)</option>
                    <option value="lead">Lead / Principal (10+ years)</option>
                  </select>
                </div>
              {/* Text area */}
              {inputMode === "text" && (
                <div>
                  <label className="block text-xs font-medium mb-2 uppercase tracking-widest" style={{ color: "var(--muted)" }}>
                    Resume Content
                  </label>
                  <textarea
                    value={resumeText}
                    onChange={(e) => setResumeText(e.target.value)}
                    placeholder="Paste your full resume here — work experience, skills, education, summary, everything..."
                    rows={13}
                    className="input-glow w-full rounded-xl border px-4 py-3 text-sm resize-none focus:outline-none"
                    style={{
                      background: "var(--cream)",
                      borderColor: "var(--border)",
                      color: "var(--ink)",
                      fontFamily: "var(--font-body)",
                      lineHeight: 1.6,
                    }}
                  />
                  <p className="text-xs mt-1" style={{ color: resumeText.length < 50 ? "var(--muted)" : "var(--green)" }}>
                    {resumeText.length} chars {resumeText.length < 50 ? `(${50 - resumeText.length} more needed)` : "✓ Ready"}
                  </p>
                </div>
              )}

              {/* PDF dropzone */}
              {inputMode === "pdf" && (
                <div
                  {...getRootProps()}
                  className={`rounded-xl border-2 border-dashed p-10 text-center cursor-pointer transition-all ${isDragActive ? "dropzone-active" : ""}`}
                  style={{
                    borderColor: isDragActive ? "var(--accent)" : "var(--border)",
                    background: isDragActive ? "rgba(200,241,53,0.15)" : "var(--cream)",
                  }}
                >
                  <input {...getInputProps()} />
                  {pdfFile ? (
                    <>
                      <p className="text-2xl mb-2">📄</p>
                      <p className="font-medium text-sm">{pdfFile.name}</p>
                      <p className="text-xs mt-1" style={{ color: "var(--muted)" }}>
                        {(pdfFile.size / 1024).toFixed(0)} KB · Click to change
                      </p>
                    </>
                  ) : (
                    <>
                      <p className="text-3xl mb-3">☁️</p>
                      <p className="font-medium text-sm mb-1">
                        {isDragActive ? "Drop it here!" : "Drag & drop your PDF"}
                      </p>
                      <p className="text-xs" style={{ color: "var(--muted)" }}>or click to browse · Max 5MB</p>
                    </>
                  )}
                </div>
              )}

              {error && (
                <div
                  className="mt-4 px-4 py-3 rounded-xl text-sm"
                  style={{ background: "var(--red-light)", color: "var(--red)" }}
                >
                  ⚠ {error}
                </div>
              )}

              <button
                onClick={handleAnalyze}
                disabled={!canAnalyze}
                className={`btn-cta ${canAnalyze ? "btn-cta--enabled" : ""} mt-6 w-full py-4 rounded-xl font-medium`}
                style={{
                  background: canAnalyze ? "var(--accent)" : "var(--border)",
                  color: canAnalyze ? "var(--accent-dark)" : "var(--muted)",
                  cursor: canAnalyze ? "pointer" : "not-allowed",
                  fontFamily: "var(--font-display)",
                  fontWeight: 600,
                  fontSize: "1.1rem",
                  transition: springTransition,
                }}
                {...(canAnalyze ? springBtn : {})}
              >
                Analyze My Resume →
              </button>
            </div>
          </>
        )}

        {/* ---- LOADING VIEW ---- */}
        {loading && (
          <div>
            <div className="text-center mb-8">
              <h2 style={{ fontFamily: "var(--font-display)", fontSize: "1.8rem" }}>
                Analyzing your resume...
              </h2>
              <p className="text-sm mt-2" style={{ color: "var(--muted)" }}>
                This takes about 15 seconds. Reading between the lines.
              </p>
            </div>
            <LoadingSkeleton />
          </div>
        )}

        {/* ---- RESULTS VIEW ---- */}
        {result && !loading && (
          <div className="animate-fade-in">
            <div className="text-center mb-8">
              <h2 style={{ fontFamily: "var(--font-display)", fontSize: "2rem", fontWeight: 700 }}>
                Your Analysis is Ready
              </h2>
              <p className="text-sm mt-1" style={{ color: "var(--muted)" }}>
                Here&apos;s what we found — and how to fix it.
              </p>
            </div>

            <div className="grid md:grid-cols-3 gap-6">
              {/* Left panel */}
              <div className="space-y-5">
                {/* Score */}
                <div
                  className="p-6 text-center animate-scale-in"
                  style={{ background: "#ffffff", border: "1px solid var(--border)", borderRadius: "1.25rem", boxShadow: "0 1px 4px rgba(0,0,0,0.06)" }}
                >
                  <p className="text-xs font-medium uppercase tracking-widest mb-4" style={{ color: "var(--muted)" }}>
                    ATS Compatibility Score
                  </p>
                  <ATSScoreRing score={result.ats_score} explanation={result.ats_score_explanation} />
                </div>

                {/* ATS Improvements */}
                {result.ats_improvements?.length > 0 && (
                  <div
                    className="p-5"
                    style={{ background: "#ffffff", border: "1px solid var(--border)", borderRadius: "1.25rem", boxShadow: "0 1px 4px rgba(0,0,0,0.06)" }}
                  >
                    <p className="text-xs font-medium uppercase tracking-widest mb-3" style={{ color: "var(--green)" }}>
                      📈 Boost Your ATS Score
                    </p>
                    <ul className="space-y-2.5">
                      {result.ats_improvements.map((tip, i) => (
                        <li key={i} className="text-sm flex gap-2">
                          <span className="shrink-0 mt-0.5" style={{ color: "var(--green)" }}>↑</span>
                          <span style={{ color: "var(--muted)" }}>{tip}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Quick wins */}
                <div
                  className="p-5"
                  style={{ background: "#ffffff", border: "1px solid var(--border)", borderRadius: "1.25rem", boxShadow: "0 1px 4px rgba(0,0,0,0.06)" }}
                >
                  <p className="text-xs font-medium uppercase tracking-widest mb-3" style={{ color: "var(--ink)" }}>
                    ⚡ Quick Wins
                  </p>
                  <ul className="space-y-2.5">
                    {result.quick_wins.map((win, i) => (
                      <li key={i} className="text-sm flex gap-2">
                        <span className="font-bold mt-0.5 shrink-0" style={{ color: "var(--ink)" }}>{i + 1}.</span>
                        <span style={{ color: "var(--muted)" }}>{win}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Missing keywords */}
                {result.keywords_missing?.length > 0 && (
                  <div
                    className="p-5"
                    style={{ background: "#ffffff", border: "1px solid var(--border)", borderRadius: "1.25rem", boxShadow: "0 1px 4px rgba(0,0,0,0.06)" }}
                  >
                    <p className="text-xs font-medium uppercase tracking-widest mb-3" style={{ color: "var(--gold)" }}>
                      🔑 Missing Keywords
                    </p>
                    <div className="flex flex-wrap gap-1.5">
                      {result.keywords_missing.map((kw, i) => (
                        <span
                          key={i}
                          className="text-xs px-3 py-1 font-medium"
                          // pill style
                          style={{ background: "var(--gold-light)", color: "var(--amber)", borderRadius: "999px" }}
                        >
                          {kw}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              {/* Right panel */}
              <div className="md:col-span-2 space-y-4">
                {/* Overall summary */}
                <div
                  className="p-5 animate-scale-in"
                  style={{ background: "var(--ink)", color: "var(--cream)", borderRadius: "1.25rem" }}
                >
                  <p className="text-xs font-medium uppercase tracking-widest mb-2 opacity-50">
                    Overall Assessment
                  </p>
                  <p className="text-sm leading-relaxed opacity-90">{result.overall_summary}</p>
                </div>

                {/* Extracted text (PDF only) */}
                {result.extracted_text && (
                  <div
                    className="p-4"
                    style={{ background: "#ffffff", border: "1px solid var(--border)", borderRadius: "1.25rem", boxShadow: "0 1px 4px rgba(0,0,0,0.06)" }}
                  >
                    <div className="flex items-center justify-between">
                      <p className="text-xs uppercase tracking-widest font-medium" style={{ color: "var(--muted)" }}>
                        Extracted Text
                      </p>
                      <button
                        onClick={() => setShowExtracted(!showExtracted)}
                        className="text-xs underline underline-offset-2"
                        style={{ color: "var(--muted)", cursor: "pointer", transition: springTransition }}
                        {...springBtn}
                      >
                        {showExtracted ? "Hide" : "Show"}
                      </button>
                    </div>
                    {showExtracted && (
                      <pre
                        className="mt-3 text-xs leading-relaxed whitespace-pre-wrap max-h-40 overflow-y-auto"
                        style={{ color: "var(--muted)" }}
                      >
                        {result.extracted_text}
                      </pre>
                    )}
                  </div>
                )}

                {/* Section cards */}
                {result.sections.map((section, i) => (
                  <SectionCard key={section.name} section={section} index={i} />
                ))}
              </div>
            </div>

            {/* Actions */}
            <div className="flex flex-col sm:flex-row gap-3 justify-center mt-8">
              <button
                onClick={handleDownload}
                className="px-6 py-3 text-sm font-medium"
                style={{
                  background: "#ffffff",
                  border: "1px solid var(--border)",
                  borderRadius: "999px",
                  color: "var(--ink)",
                  fontFamily: "var(--font-display)",
                  fontWeight: 600,
                  cursor: "pointer",
                  transition: springTransition,
                }}
                {...springBtn}
              >
                ↓ Download Report
              </button>
              <button
                onClick={handleReset}
                className="px-6 py-3 text-sm font-medium"
                style={{
                  background: "var(--accent)",
                  color: "var(--accent-dark)",
                  borderRadius: "999px",
                  fontFamily: "var(--font-display)",
                  fontWeight: 600,
                  border: "none",
                  cursor: "pointer",
                  transition: springTransition,
                }}
                {...springBtn}
              >
                Analyze Another Resume →
              </button>
            </div>
          </div>
        )}
      </main>

      <footer className="mt-16 border-t py-6 text-center" style={{ borderColor: "var(--border)" }}>
        <p className="text-xs" style={{ color: "var(--muted)" }}>
          Resumé Edge · Your data is never stored
        </p>
      </footer>
    </div>
  );
}
